version: '3.7'

services:
  reamixed:
    container_name: reamixed
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3006:3006
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PRODUCTION
      - GOOGLE_APPLICATION_CREDENTIALS=/app/upload.json
