version: '3.7'

services:

  reamixed1:
    container_name: reamixed1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 80:3006
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PRODUCTION