version: '3.7'

services:
  reamixed:
    container_name: reamixed
    build:
      context: .
      target: development
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3006:3006
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DEVELOPMENT
      - GOOGLE_APPLICATION_CREDENTIALS=/app/upload.json
  webpack:
    container_name: reamixed-webpack
    build:
      context: .
      target: development
    working_dir: /app
    volumes:
      - '.:/app'
      - '/app/node_modules'
    command: npm run build-dev
