export default [
  'Tukan/AC Trem (Tukan)',
  'Tukan/Black DeNoiser S2 (Tukan)',
  'Tukan/Blacklight Modulation S2 (Tukan)',
  'Tukan/Blue Compressor S2 (Tukan)',
  'Tukan/Bus Comp (Tukan)',
  'Tukan/Bus Comp S2 (Tukan)',
  'Tukan/CMeter Send (Tukan)',
  'Tukan/Compressor 2 (Tukan)',
  'Tukan/Compressor 3 (Tukan)',
  'Tukan/ConsoleMeter (Tukan)',
  'Tukan/DeNoiser (Tukan)',
  'Tukan/Deesser (Tukan)',
  'Tukan/Delaymachine (Tukan)',
  'Tukan/Delaymachine2 (Tukan)',
  'Tukan/Dis-Treasure (Tukan)',
  'Tukan/Dis-Treasure Compact (Tukan)',
  'Tukan/EQ 1.1 (Tukan)',
  'Tukan/EQT-1A (Tukan)',
  'Tukan/EQT-2Kan S2 (Tukan)',
  'Tukan/Envelope (Tukan)',
  'Tukan/Exciter+Sub (Tukan)',
  'Tukan/ExpGate 2 (Tukan)',
  'Tukan/Goniometer (Tukan)',
  'Tukan/Green Circles Meter S2 (Tukan)',
  'Tukan/Green Dynamic EQ S2 (Tukan)',
  'Tukan/Guitar Amp (Tukan)',
  'Tukan/Khaki Delay S2 (Tukan)',
  'Tukan/LA-1A (Tukan)',
  'Tukan/LA-2KAN S2 (Tukan)',
  'Tukan/Lexikan (Tukan)',
  'Tukan/Lexikan 2 (Tukan)',
  'Tukan/Lime Deesser S2 (Tukan)',
  'Tukan/Limiter 2 (Tukan)',
  'Tukan/Limiter 3 (Tukan)',
  'Tukan/Meter (Tukan)',
  'Tukan/Modulation (Tukan)',
  'Tukan/Modulation 2 (Tukan)',
  'Tukan/Multiband Processor (Tukan)',
  'Tukan/NC76 (Tukan)',
  'Tukan/NC76 S2 (Tukan)',
  'Tukan/NC76B (Tukan)',
  'Tukan/Orange EQ S2 (Tukan)',
  'Tukan/Peak Needle (Tukan)',
  'Tukan/PreAmp (Tukan)',
  'Tukan/Purple Gate Expander S2 (Tukan)',
  'Tukan/Red Lexikan S2 (Tukan)',
  'Tukan/SC Filter (Tukan)',
  'Tukan/SNR Meter (Tukan)',
  'Tukan/Sphinx (Tukan)',
  'Tukan/SumChannel (Tukan)',
  'Tukan/SumThing (Tukan)',
  'Tukan/SumThing SI (Tukan)',
  'Tukan/Tape (Tukan)',
  'Tukan/Tape Recorder S2 (Tukan)',
  'Tukan/Tool (Tukan)',
  'Tukan/Tool S2 (Tukan)',
  'Tukan/Turquoise Limiter S2 (Tukan)',
  'Tukan/VariBus Comp (Tukan)',
  'Tukan/VariBus Comp S2 (Tukan)',
  'Tukan/Verb Ducker (Tukan)',
  'Tukan/Violet Envelope Shaper S2 (Tukan)',
];
