name: After server responds
on:
  pull_request:
  branches:
  - master
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        - uses: actions/checkout@v2
        - name: Install modules
          run: npm install
        - name: Run tests
          run: npm test
        env: ${{ secrets.TEST_ENV_FILE }}
